### ISSUE TITLE
Moots: add toggle for gate inputs to become trigger inputs

### ISSUE THREAD

**Issue by artbody** [cosinekitty/sapphire#44]
Very nice module but in most cases i need extra modules to manage the gate of moots in that way i want.
If the gate input will also work as trigger = on and next trigger = off  i could for example use my Midi controller
for interacting 
thx

**Comment by cosinekitty** [comment]
This sounds like a great idea. I can add this as a right-click menu toggle option, to switch between gate mode (default) and trigger mode.

**Comment by cosinekitty** [comment]
@artbody Are you able to build from source? I will submit this change to VCV Rack for approval, but it usually takes them a week or two to release updates from developers. Or I can get you a zip file with which you can install Sapphire manually, if you feel comfortable with that.
