### ISSUE TITLE
Nucleus, Polynucleus, and Hiss do not appear in module browser

### ISSUE THREAD

**Issue by flarn2006** [cosinekitty/sapphire#46]
I'm running version 2.4.3 of the module, the latest version, but the modules "Nucleus", "Polynucleus", and "Hiss" are nowhere to be found.

![Screenshot showing all Sapphire modules except for the missing ones](https://github.com/cosinekitty/sapphire/assets/687313/9ce17e8b-d1f8-4fc0-9764-65239bd8b828)

I'm on the Linux version, in case it makes a difference. Haven't tested on my Mac yet.

**Comment by flarn2006** [comment]
Never mind; I thought I was subscribed to the plugin but I only had five modules in my library.

**Comment by cosinekitty** [comment]
You scared me for a minute! It felt like that one time I uploaded a YouTube video and forgot to include the audio! LOL.

I'm glad you figured out the problem...
