### ISSUE TITLE
Frolic, Glee: toggle trajectory direction

### ISSUE THREAD

**Issue by cosinekitty** [cosinekitty/sapphire#61]
It would be trivial to make Frolic and Glee trajectories go backwards by using a negative &Delta;t instead of a positive one. Basically this means calculating the velocity vector, then negating it.

Consider adding a context menu option (or even a gate input port?) to toggle the trajectory direction.

**Comment by DaveBenham** [comment]
Interesting. That might be more useful as an input, though it might disrupt
your faceplate design. An input to reverse would be analogous to a soft
sync. An input to restart from initial conditions would be a hard sync.

**Comment by DaveBenham** [comment]
Continuing the theme of a traditional oscillator, an FM (delta T) input with attenuator might be nice, especially if it can be switched between exponential and linear.

**Comment by cosinekitty** [comment]
I'm open to creating a new module with more stuff in it. Maybe we should call it... Chaos Lab!

**Comment by cosinekitty** [comment]
There is now a "flip voltage polarity" in the right-click menu for each X, Y, Z output port in Frolic, Glee, Pivot, and Rotini.
